### ISSUE TITLE
Is there an option to set the dimensions for a barcode

### ISSUE THREAD

**Issue by rvmourik** [usemarkup/BarcodeBundle#9]
Hi There,

Your bundle is working nicely, however i do have a question. Is it possible to set the width and height for the barcode?

Thanks in advance

**Comment by shieldo** [comment]
@rvmourik Apologies for the delay in response! This bundle uses the Zend Barcode component, so you should be able to specify barcode options as per the (documentation)[https://docs.zendframework.com/zend-barcode/objects/] within the bundle config.

So say you were wanting to use the `barThickWidth` option to set as, say, 5 pixels, your barcode definition could be written something like:

```yml
markup_barcode:
    definitions:
        my_definition:
            type: code128
            format: png
            barcode_options:
                barThickWidth: 5
```

You should be able to find settings that you need from that list of options for Zend Barcode.
